export const DEFAULT_PORT           = 9100;
export const DEFAULT_TIMEOUT_MS     = 3000;
export const DEFAULT_CHUNK_SIZE     = 16 * 1024;
export const DEFAULT_RETRIES        = 3;
export const DEFAULT_RETRY_DELAY_MS = 100;
export const DEFAULT_RETRY_MAX_MS   = 1000;
export const DEFAULT_RETRY_FACTOR   = 2;
export const DEFAULT_SETTLE_MS      = 500;
export const DEFAULT_DELIVERY_MODE  = "write" as const;
